### ISSUE TITLE
docker-compose build报错

### ISSUE THREAD

**Issue by WlionJ** [Qianlitp/WatchAD-Web#10]
![image](https://user-images.githubusercontent.com/42631050/89981258-26b06e00-dca6-11ea-87e3-286d50f15b90.png)
WhatchAD前面的搭建都很顺利，搭建WatchAD-Web的时候执行build报错，

**Comment by WlionJ** [comment]
![image](https://user-images.githubusercontent.com/42631050/89981351-4e9fd180-dca6-11ea-8687-81725b54b0d3.png)

**Comment by SnowSec** [comment]
解决了吗？我也是这个问题

**Comment by Qianlitp** [comment]
docker server 的版本太低了
