### ISSUE TITLE
docker-compose build ERROR: Service 'frontend' failed to build: Unknown flag: from

### ISSUE THREAD

**Issue by GeneralDuan** [Qianlitp/WatchAD-Web#14]
[root@localhost WatchAD-Web]# docker-compose build
Building frontend
Step 1/9 : FROM node:12.13.1
 ---> 7be6a8478f5f
Step 2/9 : LABEL maintainer "9ian1i <9ian1itp@gmail.com>"
 ---> Using cache
 ---> b237faed54cc
Step 3/9 : COPY . /app/
 ---> Using cache
 ---> 29e2e102f419
Step 4/9 : WORKDIR /app
 ---> Using cache
 ---> c972f54450f2
Step 5/9 : RUN npm install --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc
 ---> Using cache
 ---> 4b073ce276c4
Step 6/9 : RUN npm run build
 ---> Using cache
 ---> 161be03d2c05
Step 7/9 : FROM nginx
 ---> 0e901e68141f
Step 8/9 : LABEL maintainer "9ian1i <9ian1itp@gmail.com>"
 ---> Using cache
 ---> 960167fc43cc
Step 9/9 : COPY --from=0 /app/dist /usr/share/nginx/html
ERROR: Service 'frontend' failed to build: Unknown flag: from

**Comment by Qianlitp** [comment]
#10  看下这个，一样的问题，docker server版本太低

**Comment by GeneralDuan** [comment]
感谢您的回复 我试试看升级一下版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Qianlitp/WatchAD-Web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Qianlitp/WatchAD-Web] docker-compose build ERROR: Service 'frontend' failed to build: Unknown flag: from (Issue #14)





 
#10  看下这个，一样的问题，docker server版本太低

**Comment by GeneralDuan** [comment]
我这里搭建起来以后网页可以访问了但是里面什么都没有 也不可以设置 您可以帮看一下哪里设置不对吗？









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Qianlitp/WatchAD-Web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Qianlitp/WatchAD-Web] docker-compose build ERROR: Service 'frontend' failed to build: Unknown flag: from (Issue #14)





 
Closed #14 as completed.

**Comment by GeneralDuan** [comment]
前端这里也是127.0.0.1









------------------ 原始邮件 ------------------
发件人:                                                                                                                        "青火"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 中午11:22
***@***.***&gt;;

主题:&nbsp;回复： [Qianlitp/WatchAD-Web] docker-compose build ERROR: Service 'frontend' failed to build: Unknown flag: from (Issue #14)



我这里搭建起来以后网页可以访问了但是里面什么都没有 也不可以设置 您可以帮看一下哪里设置不对吗？









------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Qianlitp/WatchAD-Web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月13日(星期一) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Qianlitp/WatchAD-Web] docker-compose build ERROR: Service 'frontend' failed to build: Unknown flag: from (Issue #14)





 
Closed #14 as completed.
