### ISSUE TITLE
web页面不显示日志信息，es上能查询到日志信息，请问如何排查？

### ISSUE THREAD

**Issue by DeathStroke-source** [Qianlitp/WatchAD-Web#9]

**Comment by 806computervision** [comment]
你好，最后解决了么？我也遇到这个问题

**Comment by Qianlitp** [comment]
web页面不显示告警对吗？
F12看下接口是不是报错了，如果是访问后端失败，后端服务使用了本host网络模式，前端直接用127.0.0.1不用改。
如果后端报错，那么多半是数据库连接地址没有改。
